defaults: &defaults
  host: localhost
  allow_dynamic_fields: false
  include_root_in_json: false
  persist_in_safe_mode: true
  preload_models: true

development: &development
  <<: *defaults
  autocreate_indexes: true
  database: epubdummy_development

test:
  <<: *defaults
  database: epubdummy_test

production:
  <<: *development